export const menuItems = [
  {
    title: "Languages",
    submenu: [
      { title: "English" },
      { title: "Telugu" },
      { title: "Hindi" },
      { title: "Tamil" },
      { title: "Malayalam" },
      { title: "Gujarati" },
      { title: "Marati" },
      { title: "Kannada" },
    ],
  },
  {
    title: "Gener",
    submenu: [
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
    ],
  },
  {
    title: "Month",
    submenu: [
      { title: "Jan" },
      { title: "Feb" },
      { title: "Mar" },
      { title: "April" },
      { title: "May" },
      { title: "Jun" },
      { title: "July" },
      { title: "Aug" },
      { title: "Sep" },
      { title: "Oct" },
      { title: "Nav" },
      { title: "Dec" },
    ],
  },
  {
    title: "Format",
    submenu: [{ title: "3D" }, { title: "2D" }, { title: "I Max 2D" }],
  },
  {
    title: "City",
    submenu: [
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
      { title: "English" },
    ],
  },
];
